[lockfile]
schema = 1

[project]
name = "demo"
version = "0.1.0"

[project.compiler]
cc="gcc-14"
cflags=["-O3","-Wall"]
ldflags=["-s"]

[packages."fmt@10.2.1"]
name="fmt"
version="10.2.1"
source={ type="registry", url="https://registry.localpm.io", package="fmt", rev="10.2.1" }
integrity={ tarball_sha256="9f..cd" }

[packages."demo@0.1.0"]
name="demo"
version="0.1.0"
dependencies=[ { name="fmt", constraint="^10.2", resolved="10.2.1" } ]

